services:
  frontend:
    build:
      context: ../frontend
      dockerfile: /frontend/frontend/Dockerfile
    networks:
      - app_network
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: target/Dockerfile
    networks:
      - app_network
    volumes:
      - ./data:/app/data
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - frontend
      - backend
    restart: always

networks:
  app_network:
    driver: bridge