- name: Клонирование репозитория frontend
  git:
    repo: "https://github.com/DenisErichev/frontend_1.git"
    dest: "/mnt/c/Users/erich/Desktop/project/frontend"
  become: true
  tags: clone_repository

- name: Клонирование репозитория backend
  git:
    repo: "https://github.com/DenisErichev/backend_1.git"
    dest: "/mnt/c/Users/erich/Desktop/project/backend"
  become: true
  tags: clone_repository

- name: Клонирование репозитория devops
  git:
    repo: "https://github.com/DenisErichev/DevOps_1.git"
    dest: "/mnt/c/Users/erich/Desktop/project/devops"
  become: true
  tags: clone_repository

- name: Создание папки data
  file:
    path: /mnt/c/Users/erich/Desktop/project/devops/data
    state: directory
    mode: '0755'
  become: true
  tags: clone_repository

- name: Создание файла data.txt в папке data
  copy:
    content: ""
    dest: /mnt/c/Users/erich/Desktop/project/devops/data.txt
    mode: '0644'
  become: true
